[build]
  publish = "_site"
  command = "npm run build"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/"
  to = "/de"
  status = 200
  force = true # COMMENT: ensure that we always redirect